name: CI/CD Pipeline

on:
  workflow_dispatch:  # Trigger on manual workflow dispatch
    inputs:
        applicationrepo:
          description: 'Name of the React application repo'  # What's this input for?
          required: true  # Is it optional or required?
        branchOrTagName:
          description: 'Name of the branch to checkout'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show repository URL
        run: echo ${{ inputs.applicationrepo }}:${{ inputs.branchOrTagName }}
        
      - name: Checkout React App Repository
        uses: actions/checkout@v3
        
        with:
          repository: ${{ inputs.applicationrepo }}
          ref: ${{ inputs.branchOrTagName }}
          token: ${{ secrets.backstage_token }}

      - name: Package code as zip
        run: |
          zip -r react-app.zip .

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy zip to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          scp react-app.zip $EC2_USER@$EC2_HOST:~/react-app.zip

      - name: SSH to EC2 and deploy
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh $EC2_USER@$EC2_HOST << 'EOF'
          sudo unzip -o ~/react-app.zip -d ~/react-app
          sudo chown -R ec2-user:ec2-user /home/ec2-user/react-app
          cd ~/react-app
          npm install
          nohup npm start &
          EOF
